---
- name: Install Jenkins
  apt: pkg=jenkins 

- name: Install Jenkins plugins
  get_url: url=http://updates.jenkins-ci.org/latest/${item}
           dest={{ jenkins_home }}/plugins
  with_items:
    - ant.hpi
    - backup.hpi
    - build-name-setter.hpi
    - build-timeout.hpi
    - cobertura.hpi
    - credentials.hpi
    - cvs.hpi
    - dashboard-view.hpi
    - external-monitor-job.hpi
    - git.hpi
    - git-client.hpi
    - github-api.hpi
    - github-oauth.hpi
    - git-notes.hpi
    - htmlpublisher.hpi
    - javadoc.hpi
    - jenkinswalldisplay.hpi
    - jenkinswalldisplay-pom.hpi
    - jobConfigHistory.hpi
    - ldap.hpi
    - mailer.hpi
    # - maven-plugin.hpi
    - mercurial.hpi
    - nested-view.hpi
    - next-build-number.hpi
    - notification.hpi
    - pam-auth.hpi
    - parameterized-trigger.hpi
    - postbuild-task.hpi
    - rbenv.hpi
    - ruby-runtime.hpi
    - shiningpanda.hpi
    - ssh-credentials.hpi
    - ssh-slaves.hpi
    - subversion.hpi
    - thinBackup.hpi
    - timestamper.hpi
    - tmpcleaner.hpi
    - token-macro.hpi
    - translation.hpi
    - violations.hpi
  notify:
    - restart Jenkins
